version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  n8n:
    image: n8nio/n8n:1.106.3
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=${N8N_DB_CONNECTION_URL:-mongodb://mongodb:27017/n8n}
    depends_on:
      - mongodb
    volumes:
      - useteam-pt_n8n_data:/home/node/.n8n

  backend:
    build: ./backend
    container_name: kanban-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongodb
      - n8n
    volumes:
      - ./backend:/usr/src/app
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 5s

  # (Opcional) Frontend service (production build served with nginx)
  frontend:
    build:
      context: ./frontend
      target: build
    container_name: kanban-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  useteam-pt_n8n_data:
